
package ru.apertum.qsystem.server.webservice.prereg;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PreRegAPI", targetNamespace = "http://services.prereg.qsystem.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PreRegAPI {


    /**
     * 
     * @return
     *     returns java.util.List<ru.apertum.qsystem.server.webservice.prereg.Filial>
     */
    @WebMethod(operationName = "get_filials")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get_filials", targetNamespace = "http://services.prereg.qsystem.com/", className = "ru.apertum.qsystem.server.webservice.prereg.GetFilials")
    @ResponseWrapper(localName = "get_filialsResponse", targetNamespace = "http://services.prereg.qsystem.com/", className = "ru.apertum.qsystem.server.webservice.prereg.GetFilialsResponse")
    @Action(input = "http://services.prereg.qsystem.com/PreRegAPI/get_filialsRequest", output = "http://services.prereg.qsystem.com/PreRegAPI/get_filialsResponse")
    public List<Filial> getFilials();

    /**
     * 
     * @param ticketNumber
     * @param juridical
     * @param name3
     * @param comments
     * @param myIdcAccId
     * @param reasonId
     * @param phone
     * @param name2
     * @param title
     * @param name1
     * @param ticketId
     * @param email
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "set_reserve")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "set_reserve", targetNamespace = "http://services.prereg.qsystem.com/", className = "ru.apertum.qsystem.server.webservice.prereg.SetReserve")
    @ResponseWrapper(localName = "set_reserveResponse", targetNamespace = "http://services.prereg.qsystem.com/", className = "ru.apertum.qsystem.server.webservice.prereg.SetReserveResponse")
    @Action(input = "http://services.prereg.qsystem.com/PreRegAPI/set_reserveRequest", output = "http://services.prereg.qsystem.com/PreRegAPI/set_reserveResponse")
    public boolean setReserve(
        @WebParam(name = "ticket_id", targetNamespace = "")
        int ticketId,
        @WebParam(name = "reason_id", targetNamespace = "")
        int reasonId,
        @WebParam(name = "ticket_number", targetNamespace = "")
        int ticketNumber,
        @WebParam(name = "my_idc_acc_id", targetNamespace = "")
        int myIdcAccId,
        @WebParam(name = "juridical", targetNamespace = "")
        int juridical,
        @WebParam(name = "name1", targetNamespace = "")
        String name1,
        @WebParam(name = "name2", targetNamespace = "")
        String name2,
        @WebParam(name = "name3", targetNamespace = "")
        String name3,
        @WebParam(name = "title", targetNamespace = "")
        String title,
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "phone", targetNamespace = "")
        String phone,
        @WebParam(name = "comments", targetNamespace = "")
        String comments);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<ru.apertum.qsystem.server.webservice.prereg.ReserveInterval>
     */
    @WebMethod(operationName = "get_filials_free_tickets")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get_filials_free_tickets", targetNamespace = "http://services.prereg.qsystem.com/", className = "ru.apertum.qsystem.server.webservice.prereg.GetFilialsFreeTickets")
    @ResponseWrapper(localName = "get_filials_free_ticketsResponse", targetNamespace = "http://services.prereg.qsystem.com/", className = "ru.apertum.qsystem.server.webservice.prereg.GetFilialsFreeTicketsResponse")
    @Action(input = "http://services.prereg.qsystem.com/PreRegAPI/get_filials_free_ticketsRequest", output = "http://services.prereg.qsystem.com/PreRegAPI/get_filials_free_ticketsResponse")
    public List<ReserveInterval> getFilialsFreeTickets(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1);

}
