
package ru.apertum.qsystem.server.webservice.prereg;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PreRegAPI", targetNamespace = "http://services.prereg.qsystem.com/", wsdlLocation = "http://localhost:8080/QSystemPreRegAPI/PreRegAPI?wsdl")
public class PreRegAPI_Service
    extends Service
{

    private final static URL PREREGAPI_WSDL_LOCATION;
    private final static WebServiceException PREREGAPI_EXCEPTION;
    private final static QName PREREGAPI_QNAME = new QName("http://services.prereg.qsystem.com/", "PreRegAPI");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/QSystemPreRegAPI/PreRegAPI?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PREREGAPI_WSDL_LOCATION = url;
        PREREGAPI_EXCEPTION = e;
    }

    public PreRegAPI_Service() {
        super(__getWsdlLocation(), PREREGAPI_QNAME);
    }

    public PreRegAPI_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PREREGAPI_QNAME, features);
    }

    public PreRegAPI_Service(URL wsdlLocation) {
        super(wsdlLocation, PREREGAPI_QNAME);
    }

    public PreRegAPI_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PREREGAPI_QNAME, features);
    }

    public PreRegAPI_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PreRegAPI_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PreRegAPI
     */
    @WebEndpoint(name = "PreRegAPIPort")
    public PreRegAPI getPreRegAPIPort() {
        return super.getPort(new QName("http://services.prereg.qsystem.com/", "PreRegAPIPort"), PreRegAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PreRegAPI
     */
    @WebEndpoint(name = "PreRegAPIPort")
    public PreRegAPI getPreRegAPIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.prereg.qsystem.com/", "PreRegAPIPort"), PreRegAPI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PREREGAPI_EXCEPTION!= null) {
            throw PREREGAPI_EXCEPTION;
        }
        return PREREGAPI_WSDL_LOCATION;
    }

}
