/*
 * Copyright (C) 2018 Apertum Project LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ru.apertum.qsystem.client.forms;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import ru.apertum.qsystem.common.Uses;
import ru.apertum.qsystem.server.model.QUnit;
import ru.apertum.qsystem.server.model.QUnitList;
import ru.apertum.qsystem.server.model.schedule.QSchedule2;

/**
 *
 * @author zaikov
 */
public class FScheduleEditor extends javax.swing.JDialog {

    private boolean isOkClicked = false;
    private QSchedule2 schedule = null;
    
    public QSchedule2 getSchedule() {
        return schedule;
    }
    
    public boolean isOkClicked() {
        return isOkClicked;
    }
    
    private Uses.Mode mode = Uses.Mode.UNDEFINED;
    
    public FScheduleEditor(java.awt.Frame parent, boolean modal, Uses.Mode mode, QSchedule2 schedule) {        
        super(parent, modal);
        String titlePrefix = "";
        if (mode == Uses.Mode.INSERT) {
            titlePrefix = "[Добавление] ";
        } else if (mode == Uses.Mode.INSERT) {
            titlePrefix = "[Редактирование] ";
        }
        super.setTitle(titlePrefix + "Редактор расписания");
        this.mode = mode;
        if (mode == Uses.Mode.UPDATE) {
            if (schedule != null) {
                this.schedule = schedule;
            } else {
                this.setVisible(false);
            }
        }
        initComponents();
    }
    
    private void populateFields() {
//        jTextFieldScheduleName.setText(schedule.getName());
//        jComboBoxUnitValue.setSelectedItem(QUnitList.getInstance().getById(schedule.getUnitId()));
//        jComboBoxTypeValue.setSelectedIndex(schedule.getType() - 1);
//        jTextFieldMonFrom.setText(schedule.getDay1Begin() != null ? Uses.FORMAT_HH_MM.format(schedule.getDay1Begin()) : null);
//        jTextFieldMonTo.setText(schedule.getDay1End() != null ? Uses.FORMAT_HH_MM.format(schedule.getDay1End()) : null);
//        jTextFieldTueFrom.setText(schedule.getDay2Begin() != null ? Uses.FORMAT_HH_MM.format(schedule.getDay2Begin()) : null);
//        jTextFieldTueTo.setText(schedule.getDay2End() != null ? Uses.FORMAT_HH_MM.format(schedule.getDay2End()) : null);
//        jTextFieldWedFrom.setText(schedule.getDay3Begin() != null ? Uses.FORMAT_HH_MM.format(schedule.getDay3Begin()) : null);
//        jTextFieldWedTo.setText(schedule.getDay3End() != null ? Uses.FORMAT_HH_MM.format(schedule.getDay3End()) : null);
//        jTextFieldThuFrom.setText(schedule.getDay4Begin() != null ? Uses.FORMAT_HH_MM.format(schedule.getDay4Begin()) : null);
//        jTextFieldThuTo.setText(schedule.getDay4End() != null ? Uses.FORMAT_HH_MM.format(schedule.getDay4End()) : null);
//        jTextFieldFriFrom.setText(schedule.getDay5Begin() != null ? Uses.FORMAT_HH_MM.format(schedule.getDay5Begin()) : null);
//        jTextFieldFriTo.setText(schedule.getDay5End() != null ? Uses.FORMAT_HH_MM.format(schedule.getDay5End()) : null);
//        jTextFieldSatFrom.setText(schedule.getDay6Begin() != null ? Uses.FORMAT_HH_MM.format(schedule.getDay6Begin()) : null);
//        jTextFieldSatTo.setText(schedule.getDay6End() != null ? Uses.FORMAT_HH_MM.format(schedule.getDay6End()) : null);
//        jTextFieldSunFrom.setText(schedule.getDay7Begin() != null ? Uses.FORMAT_HH_MM.format(schedule.getDay7Begin()) : null);
//        jTextFieldSunTo.setText(schedule.getDay7End() != null ? Uses.FORMAT_HH_MM.format(schedule.getDay7End()) : null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSheduleTitle = new javax.swing.JLabel();
        jLabelTypeTitle = new javax.swing.JLabel();
        jLabelUnitTitle = new javax.swing.JLabel();
        jComboBoxUnitValue = new javax.swing.JComboBox<>();
        jComboBoxTypeValue = new javax.swing.JComboBox<>();
        jTextFieldScheduleName = new javax.swing.JTextField();
        jLabelMonTitle = new javax.swing.JLabel();
        jTextFieldMonTo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldMonFrom = new javax.swing.JTextField();
        jLabelTueTitle = new javax.swing.JLabel();
        jTextFieldTueFrom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTueTo = new javax.swing.JTextField();
        jLabelWedTitle = new javax.swing.JLabel();
        jTextFieldWedFrom = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldWedTo = new javax.swing.JTextField();
        jLabelThuTitle = new javax.swing.JLabel();
        jTextFieldThuFrom = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldThuTo = new javax.swing.JTextField();
        jLabelFriTitle = new javax.swing.JLabel();
        jTextFieldFriFrom = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldFriTo = new javax.swing.JTextField();
        jLabelSatTitle = new javax.swing.JLabel();
        jTextFieldSatFrom = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldSatTo = new javax.swing.JTextField();
        jLabelSunTitle = new javax.swing.JLabel();
        jTextFieldSunFrom = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldSunTo = new javax.swing.JTextField();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 368));
        setPreferredSize(new java.awt.Dimension(300, 368));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabelSheduleTitle.setText("Название плана:");
        getContentPane().add(jLabelSheduleTitle);
        jLabelSheduleTitle.setBounds(10, 14, 85, 14);

        jLabelTypeTitle.setText("Тип:");
        getContentPane().add(jLabelTypeTitle);
        jLabelTypeTitle.setBounds(10, 40, 22, 14);

        jLabelUnitTitle.setText("Отделение:");
        getContentPane().add(jLabelUnitTitle);
        jLabelUnitTitle.setBounds(10, 66, 61, 14);

        getContentPane().add(jComboBoxUnitValue);
        jComboBoxUnitValue.setBounds(109, 63, 162, 20);

        jComboBoxTypeValue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "СПиАО", "СЦ" }));
        getContentPane().add(jComboBoxTypeValue);
        jComboBoxTypeValue.setBounds(109, 37, 162, 20);
        getContentPane().add(jTextFieldScheduleName);
        jTextFieldScheduleName.setBounds(109, 11, 162, 20);

        jLabelMonTitle.setText("Понедельник:");
        getContentPane().add(jLabelMonTitle);
        jLabelMonTitle.setBounds(10, 109, 72, 14);
        getContentPane().add(jTextFieldMonTo);
        jTextFieldMonTo.setBounds(204, 106, 65, 20);

        jLabel5.setText("—");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(184, 109, 10, 14);
        getContentPane().add(jTextFieldMonFrom);
        jTextFieldMonFrom.setBounds(109, 106, 65, 20);

        jLabelTueTitle.setText("Вторник:");
        getContentPane().add(jLabelTueTitle);
        jLabelTueTitle.setBounds(10, 135, 46, 14);
        getContentPane().add(jTextFieldTueFrom);
        jTextFieldTueFrom.setBounds(109, 132, 65, 20);

        jLabel7.setText("—");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(184, 135, 10, 14);
        getContentPane().add(jTextFieldTueTo);
        jTextFieldTueTo.setBounds(204, 132, 65, 20);

        jLabelWedTitle.setText("Среда:");
        getContentPane().add(jLabelWedTitle);
        jLabelWedTitle.setBounds(10, 161, 36, 14);
        getContentPane().add(jTextFieldWedFrom);
        jTextFieldWedFrom.setBounds(109, 158, 65, 20);

        jLabel9.setText("—");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(184, 161, 10, 14);
        getContentPane().add(jTextFieldWedTo);
        jTextFieldWedTo.setBounds(204, 158, 65, 20);

        jLabelThuTitle.setText("Четверг:");
        getContentPane().add(jLabelThuTitle);
        jLabelThuTitle.setBounds(10, 187, 46, 14);
        getContentPane().add(jTextFieldThuFrom);
        jTextFieldThuFrom.setBounds(109, 184, 65, 20);

        jLabel11.setText("—");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(184, 187, 10, 14);
        getContentPane().add(jTextFieldThuTo);
        jTextFieldThuTo.setBounds(204, 184, 65, 20);

        jLabelFriTitle.setText("Пятница:");
        getContentPane().add(jLabelFriTitle);
        jLabelFriTitle.setBounds(10, 213, 47, 14);
        getContentPane().add(jTextFieldFriFrom);
        jTextFieldFriFrom.setBounds(109, 210, 65, 20);

        jLabel13.setText("—");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(184, 213, 10, 14);
        getContentPane().add(jTextFieldFriTo);
        jTextFieldFriTo.setBounds(204, 210, 65, 20);

        jLabelSatTitle.setText("Суббота:");
        getContentPane().add(jLabelSatTitle);
        jLabelSatTitle.setBounds(10, 239, 47, 14);
        getContentPane().add(jTextFieldSatFrom);
        jTextFieldSatFrom.setBounds(109, 236, 65, 20);

        jLabel15.setText("—");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(184, 239, 10, 14);
        getContentPane().add(jTextFieldSatTo);
        jTextFieldSatTo.setBounds(204, 236, 65, 20);

        jLabelSunTitle.setText("Воскресенье:");
        getContentPane().add(jLabelSunTitle);
        jLabelSunTitle.setBounds(10, 265, 68, 14);
        getContentPane().add(jTextFieldSunFrom);
        jTextFieldSunFrom.setBounds(109, 262, 65, 20);

        jLabel17.setText("—");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(184, 265, 10, 14);
        getContentPane().add(jTextFieldSunTo);
        jTextFieldSunTo.setBounds(204, 262, 65, 20);

        jButtonOk.setText("ОК");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOk);
        jButtonOk.setBounds(157, 293, 71, 23);

        jButtonCancel.setText("Отмена");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancel);
        jButtonCancel.setBounds(50, 293, 71, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jComboBoxUnitValue.setModel(new DefaultComboBoxModel(QUnitList.getInstance().getItems().toArray()));
        if (mode == Uses.Mode.INSERT) {
            schedule = null;
        } else if (mode == Uses.Mode.UPDATE) {
            populateFields();
        }
        isOkClicked = false;
    }//GEN-LAST:event_formWindowOpened

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
//        if (mode == Uses.Mode.INSERT) {
//            schedule = new QSchedule2();
//        }
//        schedule.setName(jTextFieldScheduleName.getText());
//        schedule.setUnitId(((QUnit)jComboBoxUnitValue.getSelectedItem()).getId().intValue());
//        //в combobox-е СПиАО имеет индекс 0, а СЦ - 1
//        //так как СПиАО в электронной очереди имеет значение 1, а СЦ - 2,
//        //то нужно увеличить на единицу, чтобы получить праивльное значение
//        schedule.setType(jComboBoxTypeValue.getSelectedIndex() + 1);
//        try {
//            schedule.setDay1Begin(Uses.FORMAT_HH_MM.parse(jTextFieldMonFrom.getText()));
//            schedule.setDay1End(Uses.FORMAT_HH_MM.parse(jTextFieldMonTo.getText()));
//            schedule.setDay2Begin(Uses.FORMAT_HH_MM.parse(jTextFieldTueFrom.getText()));
//            schedule.setDay2End(Uses.FORMAT_HH_MM.parse(jTextFieldTueTo.getText()));
//            schedule.setDay3Begin(Uses.FORMAT_HH_MM.parse(jTextFieldWedFrom.getText()));
//            schedule.setDay3End(Uses.FORMAT_HH_MM.parse(jTextFieldWedTo.getText()));
//            schedule.setDay4Begin(Uses.FORMAT_HH_MM.parse(jTextFieldThuFrom.getText()));
//            schedule.setDay4End(Uses.FORMAT_HH_MM.parse(jTextFieldThuTo.getText()));
//            schedule.setDay5Begin(Uses.FORMAT_HH_MM.parse(jTextFieldFriFrom.getText()));
//            schedule.setDay5End(Uses.FORMAT_HH_MM.parse(jTextFieldFriTo.getText()));
//            schedule.setDay6Begin(Uses.FORMAT_HH_MM.parse(jTextFieldSatFrom.getText()));
//            schedule.setDay6End(Uses.FORMAT_HH_MM.parse(jTextFieldSatTo.getText()));
//            schedule.setDay7Begin(Uses.FORMAT_HH_MM.parse(jTextFieldSunFrom.getText()));
//            schedule.setDay7End(Uses.FORMAT_HH_MM.parse(jTextFieldSunTo.getText()));
//        } catch(Exception ex) {
//            JOptionPane.showMessageDialog(this, "Неправильный формат времени или не заполнены все значения интервалов.");
//            return;
//        }
//        isOkClicked = true;
//        this.setVisible(false);
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        isOkClicked = false;
        schedule = null;
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JComboBox<String> jComboBoxTypeValue;
    private javax.swing.JComboBox<String> jComboBoxUnitValue;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFriTitle;
    private javax.swing.JLabel jLabelMonTitle;
    private javax.swing.JLabel jLabelSatTitle;
    private javax.swing.JLabel jLabelSheduleTitle;
    private javax.swing.JLabel jLabelSunTitle;
    private javax.swing.JLabel jLabelThuTitle;
    private javax.swing.JLabel jLabelTueTitle;
    private javax.swing.JLabel jLabelTypeTitle;
    private javax.swing.JLabel jLabelUnitTitle;
    private javax.swing.JLabel jLabelWedTitle;
    private javax.swing.JTextField jTextFieldFriFrom;
    private javax.swing.JTextField jTextFieldFriTo;
    private javax.swing.JTextField jTextFieldMonFrom;
    private javax.swing.JTextField jTextFieldMonTo;
    private javax.swing.JTextField jTextFieldSatFrom;
    private javax.swing.JTextField jTextFieldSatTo;
    private javax.swing.JTextField jTextFieldScheduleName;
    private javax.swing.JTextField jTextFieldSunFrom;
    private javax.swing.JTextField jTextFieldSunTo;
    private javax.swing.JTextField jTextFieldThuFrom;
    private javax.swing.JTextField jTextFieldThuTo;
    private javax.swing.JTextField jTextFieldTueFrom;
    private javax.swing.JTextField jTextFieldTueTo;
    private javax.swing.JTextField jTextFieldWedFrom;
    private javax.swing.JTextField jTextFieldWedTo;
    // End of variables declaration//GEN-END:variables
}
