/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.apertum.qsystem.client.forms;

import java.awt.Dimension;
import javax.swing.JDialog;
import javax.swing.JFrame;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;
import ru.apertum.qsystem.common.QLog;
import ru.apertum.qsystem.common.model.INetProperty;

/**
 *
 * @author dsavchenko
 */
public class FSendToBank  extends JDialog  {

    /**
     * Creates new form FSendToBank
     */
    public FSendToBank(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setSize(new Dimension(400,150));
        setResizable(false);
        initComponents();
    }

    public void init() {
       checkBoxBack.setSelected(true); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkBoxBack = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        checkBoxBack.setSelected(true);
        checkBoxBack.setLabel("Вернуть  после оплаты");
        checkBoxBack.setName("checkBoxBack"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(FSendToBank.class, this);
        jButton1.setAction(actionMap.get("onOkClicked")); // NOI18N
        jButton1.setText("OK");
        jButton1.setName("jButton1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkBoxBack, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(checkBoxBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void onOkClicked() {
        clientReturnChecked = checkBoxBack.isSelected();
        Ok = true;
        this.setVisible(false);
    }

   public boolean isOK() {
        return Ok;
    }
      /**
     * Используемая ссылка на диалоговое окно.
     */
    public boolean Ok;
    public boolean clientReturnChecked;
    
        /**
     * Выбор услуги для перенаправления.
     *
     * @param netProperty свойства коннекта
     * @param owner относительно этого контрола модальность и позиционирование
     * @param tempComments это если были комменты с прошлых редиректов
     * @param onlyComments показывать или нет что-то другое ктоме вводе комментария
     * @return класс полусения свойств
     */
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBoxBack;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
