/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.apertum.qsystem.client.forms;

import java.awt.Dimension;

/**
 *
 * @author zaikov
 */
public class FSendToBank2 extends javax.swing.JDialog {

    private boolean isOkClicked = false;
    private boolean needReturnAfterPayment = false;
    private boolean isMine = false;
    private boolean isNewBankSendingEnabled = false;
    private final java.awt.Dimension dimension;
    
    public int getPaymentType() {
        return cbPaymentType.getSelectedIndex();
    }
    
    public boolean isOkClicked() {
        return isOkClicked;
    }
    
    public boolean needReturnAfterPayment() {
        return needReturnAfterPayment;
    }
    
    public boolean isMine() {
        return isMine;
    }
    
    /**
     * Creates new form FSendToBank2
     * @param parent
     * @param modal
     * @param isNewBankSendingEnabled
     */
    public FSendToBank2(java.awt.Frame parent, boolean modal, boolean isNewBankSendingEnabled) {
        super(parent, modal);
        
        this.isNewBankSendingEnabled = isNewBankSendingEnabled;
        setTitle("Отправить на оплату");
        
        if (this.isNewBankSendingEnabled) {
            dimension = new java.awt.Dimension(347, 185);
        } else {
            dimension = new java.awt.Dimension(347, 137);
        }
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        checkBoxReturnAfterPayment = new javax.swing.JCheckBox();
        checkBoxIsMine = new javax.swing.JCheckBox();
        cbPaymentType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setPreferredSize(dimension);
        setResizable(false);
        setSize(dimension);

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        checkBoxReturnAfterPayment.setSelected(true);
        checkBoxReturnAfterPayment.setText("Вернуть после оплаты");
        checkBoxReturnAfterPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxReturnAfterPaymentActionPerformed(evt);
            }
        });

        checkBoxIsMine.setSelected(true);
        checkBoxIsMine.setText("Это только мой клиент");

        cbPaymentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Оплата в кассе АПБ", "Оплата другим способом" }));

        jLabel1.setText("Способ оплаты:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbPaymentType, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBoxIsMine)
                            .addComponent(checkBoxReturnAfterPayment))
                        .addGap(66, 66, 66)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkBoxReturnAfterPayment)
                        .addGap(33, 33, 33)
                        .addComponent(checkBoxIsMine))
                    .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbPaymentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        isOkClicked = true;
        needReturnAfterPayment = checkBoxReturnAfterPayment.isSelected();
        isMine = checkBoxIsMine.isSelected();
        
        this.setVisible(false);
    }//GEN-LAST:event_btnOkActionPerformed

    private void checkBoxReturnAfterPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxReturnAfterPaymentActionPerformed
        if (checkBoxReturnAfterPayment.isSelected()) {
            checkBoxIsMine.setEnabled(true);
        } else {
            checkBoxIsMine.setEnabled(false);
            checkBoxIsMine.setSelected(false);
        }
        checkBoxIsMine.setSelected(checkBoxReturnAfterPayment.isSelected());
    }//GEN-LAST:event_checkBoxReturnAfterPaymentActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> cbPaymentType;
    private javax.swing.JCheckBox checkBoxIsMine;
    private javax.swing.JCheckBox checkBoxReturnAfterPayment;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
