/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.apertum.qsystem.client.forms;

import java.awt.Dimension;

/**
 *
 * @author zaikov
 */
public class FSendToBank2 extends javax.swing.JDialog {

    private boolean isOkClicked = false;
    private boolean needReturnAfterPayment = false;
    private boolean isMine = false;
    
    public boolean isOkClicked() {
        return isOkClicked;
    }
    
    public boolean needReturnAfterPayment() {
        return needReturnAfterPayment;
    }
    
    public boolean isMine() {
        return isMine;
    }
    
    /**
     * Creates new form FSendToBank2
     */
    public FSendToBank2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setTitle("Отправить на оплату");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        checkBoxReturnAfterPayment = new javax.swing.JCheckBox();
        checkBoxIsMine = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setPreferredSize(new java.awt.Dimension(335, 144));
        setResizable(false);
        setSize(new java.awt.Dimension(315, 115));

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        checkBoxReturnAfterPayment.setSelected(true);
        checkBoxReturnAfterPayment.setText("Вернуть после оплаты");
        checkBoxReturnAfterPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxReturnAfterPaymentActionPerformed(evt);
            }
        });

        checkBoxIsMine.setSelected(true);
        checkBoxIsMine.setText("Это только мой клиент");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxIsMine)
                    .addComponent(checkBoxReturnAfterPayment))
                .addGap(54, 54, 54)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkBoxReturnAfterPayment)
                        .addGap(24, 24, 24)
                        .addComponent(checkBoxIsMine))
                    .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        isOkClicked = true;
        needReturnAfterPayment = checkBoxReturnAfterPayment.isSelected();
        isMine = checkBoxIsMine.isSelected();
        
        this.setVisible(false);
    }//GEN-LAST:event_btnOkActionPerformed

    private void checkBoxReturnAfterPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxReturnAfterPaymentActionPerformed
        if (checkBoxReturnAfterPayment.isSelected()) {
            checkBoxIsMine.setEnabled(true);
        } else {
            checkBoxIsMine.setEnabled(false);
            checkBoxIsMine.setSelected(false);
        }
        checkBoxIsMine.setSelected(checkBoxReturnAfterPayment.isSelected());
    }//GEN-LAST:event_checkBoxReturnAfterPaymentActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JCheckBox checkBoxIsMine;
    private javax.swing.JCheckBox checkBoxReturnAfterPayment;
    // End of variables declaration//GEN-END:variables
}
