/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.apertum.qsystem.client.forms;

import java.util.ArrayList;
import java.util.Enumeration;
import java.util.LinkedList;
import java.util.List;
import java.util.Objects;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;
import ru.apertum.qsystem.common.NetCommander;
import ru.apertum.qsystem.common.exceptions.ClientException;
import ru.apertum.qsystem.common.model.INetProperty;
import ru.apertum.qsystem.server.model.QService;
import static ru.apertum.qsystem.server.model.QService.STATUS_FOR_USING;
import ru.apertum.qsystem.server.model.QServiceTree;

/**
 *
 * @author zaikov
 */
public class FServiceCompletion extends javax.swing.JDialog {
    
    private QService defaultService;

    /**
     * Creates new form FServiceCompletion
     * @param netProperty
     * @param parent
     * @param modal
     * @param defaultService услуга, которую нужно выделить в дереве по умолчанию
     */
    public FServiceCompletion(INetProperty netProperty, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        this.setTitle("Выбор услуг оказанных клиенту");
        loadContent(netProperty);
        initComponents();
        
//        jTree1.setUI( new MySelectionTreeUI() );
//        jTree1.setSelectionModel(new MyTreeSelectionModel());
    }
    
    public void setDefaultService(QService defaultService) {
        this.defaultService = defaultService;
    }
    
    private void setDefaults() {
        jTree1.setModel(new FRedirect.ServiceTreeModel());
        //обходим все узлы и выделяем дефолтную услугу
        visitAllNodes(jTree1);
    }
    
    public void visitAllNodes(JTree tree) {
        TreeNode root = (TreeNode) tree.getModel().getRoot();
        visitAllNodes(root);
    }
    
    public void visitAllNodes(TreeNode node) {
        if (node.getChildCount() >= 0) {
            for (Enumeration e = node.children(); e.hasMoreElements();) {
                DefaultMutableTreeNode n = (DefaultMutableTreeNode)e.nextElement();
                QService service = (QService)n;
                //если нашли нужный узел, то выделяем его
                if (Objects.equals(service.getId(), defaultService.getId())) {
                    TreePath path = new TreePath(n.getPath());
                    jTree1.setSelectionPath(path);
                }
                visitAllNodes(n);
            }
        }
    }
    
    /**
     * Получить список выбранных услуг
     * @return 
     */
    public List<QService> getSelectedServices() {
        List<QService> selectedServices = new ArrayList<>();
        for (TreePath path : jTree1.getSelectionPaths()) {
            QService service = (QService)path.getLastPathComponent();
            if (service.isLeaf()) {
                selectedServices.add(service);
            }
        }
        return selectedServices;
    }
    
    private void loadContent(INetProperty netProperty) {
        if (FRedirect.ServiceTreeModel.list == null) {
            final QService service = NetCommander.getServiсes(netProperty).getRoot();
            if (service == null) {
                throw new ClientException("Невозможно получить список предлагаемых услуг.");
            }
            final LinkedList<QService> list = new LinkedList<>();
            QServiceTree.sailToStorm(service, (TreeNode service1) -> {
                final QService ser = (QService) service1;
                if (STATUS_FOR_USING.contains(ser.getStatus())) {
                    list.add(ser);
                }
            });
            // дело в том, что из всего дерева услуг надо убрать заглушки и неактивные чтобы в них не перенаправлять.
            // а дерево строится не по указанию на предка, а от корня по дочерним.
            // вот и приходится удалять из дочерних.
            list.stream().forEach((ser) -> {
                final LinkedList<QService> del = new LinkedList<>();
                ser.getChildren().stream().filter((che) -> (!STATUS_FOR_USING.contains(che.getStatus()))).forEach((che) -> {
                    del.add(che);
                });
                del.stream().forEach((qService) -> {
                    ser.remove(qService);
                });
            });
            FRedirect.ServiceTreeModel.list = list; // это две связанные строчки
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        jButton1.setText("Сохранить");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        setDefaults();
    }//GEN-LAST:event_formComponentShown

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
