/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.apertum.qsystem.client.forms;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import ru.apertum.qsystem.client.common.ClientNetProperty;
import ru.apertum.qsystem.common.NetCommander;
import ru.apertum.qsystem.common.model.INetProperty;
import ru.apertum.qsystem.server.QSession;
import ru.apertum.qsystem.server.model.QSessionList;

/**
 *
 * @author zaikov
 */
public class FSessionManager extends javax.swing.JFrame {

    private static INetProperty netProperty;
    private QSessionList sessionsListModel = new QSessionList();
    
    public FSessionManager() {
        initComponents();
        loadRelativeData();
        
        jListSessions.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                selectClickedItem(e);
            }
        });
        jListSessions.setComponentPopupMenu(jPopupMenu1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItemRemove = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSessions = new javax.swing.JList();
        jButtonReload = new javax.swing.JButton();

        jMenuItemRemove.setText("Удалить сессию");
        jMenuItemRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRemoveActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItemRemove);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jListSessions);

        jButtonReload.setText("Обновить");
        jButtonReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonReload)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonReload)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReloadActionPerformed
        loadRelativeData();
    }//GEN-LAST:event_jButtonReloadActionPerformed

    private void jMenuItemRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRemoveActionPerformed
        QSession session = (QSession)jListSessions.getSelectedValue();
        removeSession(session);
    }//GEN-LAST:event_jMenuItemRemoveActionPerformed

    private void selectClickedItem(MouseEvent e) {
        if (SwingUtilities.isRightMouseButton(e)) {
            JList list = (JList)e.getSource();
            int row = list.locationToIndex(e.getPoint());
            list.setSelectedIndex(row);
        }
    }
    
    private void removeSession(QSession session) {
        if (JOptionPane.showConfirmDialog(this,
                            "<html>Уверены, что хотите удалить сессию " + session.toString().replace("<html>", "").replace("</html>", "") + "?</html>",
                            "Внимание!",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.INFORMATION_MESSAGE) != 0) {
            return;
        }
        try {
            NetCommander.removeSession(netProperty, session.getUser().getId());
            sessionsListModel.removeElement(session);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                                          "Сессия не была удалена!",
                                          "Внимание!",
                                          JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        netProperty = new ClientNetProperty(args);
        
        FSessionManager sm = new FSessionManager();
        sm.setLocationRelativeTo(null);
        sm.setTitle("Менеджер сессий пользователей");
        sm.setResizable(false);
        sm.setVisible(true);
    }
    
    private void loadRelativeData() {
        try {
            sessionsListModel = new QSessionList(NetCommander.getSessions(netProperty));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                                          "Ошибка получения списка сессий",
                                          "Внимание!",
                                          JOptionPane.ERROR_MESSAGE);
        }
        jListSessions.setModel(sessionsListModel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReload;
    private javax.swing.JList jListSessions;
    private javax.swing.JMenuItem jMenuItemRemove;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
