/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.apertum.qsystem.client.forms;

import java.awt.Frame;
import java.io.BufferedInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import javax.swing.JOptionPane;
import ru.apertum.qsystem.About;
import ru.apertum.qsystem.common.QLog;
import ru.apertum.qsystem.common.exceptions.ClientException;


/**
 *
 * @author zaikov
 */
public class FUpdate extends javax.swing.JDialog {
    
    private Frame parent;
    private boolean modal;
    private String completeUpdateMessage = "Возникла ошибка во время обновления приложения.";

    public FUpdate(Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        this.modal = modal;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateStateLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        restartButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(322, 106));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(322, 106));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        updateStateLabel.setText("Обновление программы...");

        progressBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        progressBar.setFocusable(false);
        progressBar.setIndeterminate(true);

        restartButton.setText("ОК");
        restartButton.setEnabled(false);
        restartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateStateLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(restartButton)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(updateStateLabel)
                .addGap(1, 1, 1)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(restartButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * unzip the archive into output folder
     * @param zipFile input zip file
     * @param outputFolder zip file output folder
     */
    public void unZipInto(String zipFile, String outputFolder) {
        
        byte[] buffer = new byte[1024];

        try {
            //create output directory is not exists
            File folder = new File(outputFolder);
            if (!folder.exists()) {
                folder.mkdir();
            }
            
            //get the zip file content
            try (ZipInputStream zis = new ZipInputStream(new FileInputStream(zipFile))) {
                //get the zipped file list entry
                ZipEntry ze = zis.getNextEntry();
                
                while (ze != null) {
                    String fileName = ze.getName();
                    File newFile = new File(outputFolder + File.separator + fileName);
                    
                    if (ze.isDirectory()) {
                        newFile.mkdirs();
                    } else {
                        try (FileOutputStream fos = new FileOutputStream(newFile)) {
                            int len;
                            while ((len = zis.read(buffer)) > 0) {
                                fos.write(buffer, 0, len);
                            }
                        }
                    }
                    ze = zis.getNextEntry();
                }

                zis.closeEntry();
            }
       } catch(IOException e) {
           JOptionPane.showMessageDialog(parent, "Ошибка в процессе работы с архивом.\n" + e.getMessage());
           QLog.l().logger().error("Ошибка в процессе работы с архивом", e);
       }
    }
    
    private void runUpdate() throws Exception {
        //имя архива с обновлением
        String archiveName = "QSystem.zip";
        //пусть к папке запущенного ПО
        String appPath = About.appPath + File.separator + "dist";
        //путь для сохранения файлов обновления (переменная окружения TEMP)
        String tempFolderPath = System.getenv("TEMP") == null ? "C:\\temp" : System.getenv("TEMP");
        //путь к архиву из которого будет обновляться программа
        String tempZipFilePath = tempFolderPath + File.separator + archiveName;
        
        URL link = null;
        InputStream is = null;

        try {
            link = new URL("file://10.5.0.2/ProgsUpdate/QSystem-autoupdate/" + archiveName);
            is = new BufferedInputStream(link.openStream());
        } catch(IOException e) {
            QLog.l().logger().error("Ошибка в процессе обновления ПО.", e);
            throw new ClientException("Ошибка в процессе обновления ПО.", e);
        }
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        byte[] buf = new byte[1024];
        int n = 0;
        try {
            while ((n = is.read(buf)) != -1) {
                out.write(buf, 0, n);
            }
            out.close();
            is.close();
        } catch(IOException e) {
            QLog.l().logger().error("Ошибка чтения файла из потока.", e);
            throw new ClientException("Ошибка чтения файла из потока.", e);
        }

        byte[] response = out.toByteArray();

        try {
            FileOutputStream fos = new FileOutputStream(tempZipFilePath);
            fos.write(response);
            fos.close();
        } catch(IOException e) {
//            JOptionPane.showMessageDialog(this, "Ошибка записи в файл.\n" + e.getMessage());
            QLog.l().logger().error("Ошибка записи в файл.", e);
            throw new ClientException("Ошибка записи в файл.", e);
        }

        //распаковываем файлы архива в папку откуда запускается программа
        unZipInto(tempZipFilePath, appPath);

        //удаляем архив из временной папки
        File fileToRemove = new File(tempZipFilePath);
        fileToRemove.delete();
        
        //если дошли без ошибок до этой строки, то обновление успешно
        completeUpdateMessage = "Обновление завершено. Требуется перезапуск программы.";
    }
    
    private void completeUpdate() {
        progressBar.setIndeterminate(false);
        progressBar.setValue(100);
        updateStateLabel.setText(completeUpdateMessage);
        restartButton.setEnabled(true);
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            //запускаем процесс обновления
            runUpdate();
        } catch(Exception ce) {
            JOptionPane.showMessageDialog(this, ce.getMessage(), "Ошибка", JOptionPane.ERROR_MESSAGE);
        } finally {
            //финальные штрихи после завершения обновления
            completeUpdate();
        }
    }//GEN-LAST:event_formWindowOpened

    private void restartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartButtonActionPerformed
//        try {
//            Runtime.getRuntime().exec("cmd /c" + About.appPath + File.separator + "StartClient.bat");
//        } catch (IOException e) {
//            QLog.l().logger().error("Ошибка перезапуска ПО.", e);
//            JOptionPane.showMessageDialog(this, "Ошибка перезапуска ПО.\n" + e.getMessage());
//        } finally {
            System.exit(0);
//        }
    }//GEN-LAST:event_restartButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JToggleButton restartButton;
    private javax.swing.JLabel updateStateLabel;
    // End of variables declaration//GEN-END:variables
}
