/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.apertum.qsystem.client.forms;

import java.util.LinkedList;
import java.util.Objects;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.DefaultListModel;
import ru.apertum.qsystem.client.common.UsersListRenderer;
import ru.apertum.qsystem.common.NetCommander;
import ru.apertum.qsystem.common.Uses;
import ru.apertum.qsystem.common.model.INetProperty;
import ru.apertum.qsystem.server.model.QUser;

/**
 *
 * @author zaikov
 */
public class RedirectionUsersWindow extends javax.swing.JDialog {
    
    private final INetProperty netProperty;
    private final String comment;
    private Timer refreshUsersTimer;
    private final int unitId;
    //1 - абон. зал, 2 - СЦ
    private int pointType;
    private QUser selectedUser;
    private QUser receivedUser;
    private boolean isCancelled = false;

    public QUser getSelectedUser() {
        return selectedUser;
    }
    
    public boolean isCancelled() {
        return isCancelled;
    }
    
    public boolean isRedirectBack() {
        return redirectBackCheckbox.isSelected();
    }
    
    public String getComment() {
        return commentTextArea.getText();
    }
    
    public long getSelectedService() {
        switch (pointType) {
            case Uses.POINT_TYPE_ABO:
                return Uses.SERVICE_ABO_ID;
                
            case Uses.POINT_TYPE_SC:
                return Uses.SERVICE_SC_ID;
            
            case Uses.POINT_TYPE_CONSULTANT:
                return Uses.SERVICE_CONSULTATION_ID;
                
            default:
                return Uses.SERVICE_ABO_ID;
        }
    }
    
    public RedirectionUsersWindow(java.awt.Frame parent, boolean modal, INetProperty netProperty, QUser user, int unitId, int pointType, String comment) {
        super(parent, modal);
        initComponents();
        
        setTitle("Перенаправление");
        setLocationRelativeTo(parent);
        
        this.netProperty = netProperty;
        this.comment = comment;
        this.unitId = unitId;
        this.pointType = pointType;
        this.receivedUser = user;
        
        setDefaults();
        startRefreshUsersTimer();
        
        UsersListRenderer renderer = new UsersListRenderer();
        usersList.setCellRenderer(renderer);
    }
    
    private void setDefaults() {
        commentTextArea.setText((comment == null || comment.isEmpty() ? "" : "\n\n__________________________________\n") + comment);
        redirectBackCheckbox.setSelected(false);
        switch (pointType) {
            case Uses.POINT_TYPE_ABO:
                aboRadioButton.setSelected(true);
                break;
                
            case Uses.POINT_TYPE_SC:
                scRadioButton.setSelected(true);
                break;
                
            case Uses.POINT_TYPE_CONSULTANT:
                consultantRadioButton.setSelected(true);
                break;
                
            default:
                aboRadioButton.setSelected(true);
        }
    }
    
    private void startRefreshUsersTimer() {
        TimerTask task = new TimerTask() {
            
            @Override
            public void run() {
                refreshUsers();
            }
        };
        refreshUsersTimer = new Timer();
        refreshUsersTimer.scheduleAtFixedRate(task, 0L, 5000L);
    }
    
    private void refreshUsers() {
        QUser selUser = usersList.getSelectedValue();
        
        final LinkedList<QUser> users = NetCommander.getUsers(netProperty, unitId, pointType);

        if (users == null) {
            return;
        }

        DefaultListModel<QUser> model = new DefaultListModel<>();
        users.forEach(user -> {
            if ( !Objects.equals(receivedUser.getId(), user.getId()) && user.getShadow() != null && !user.isTechWork() && !user.isContinueServicing() ) {
                model.addElement(user);
            }
        });
        usersList.setModel(model);

        if (selUser == null) {
            return;
        }
        
        //выделяем юзера, который был выделен до обновления
        for (int i = 0; i < usersList.getModel().getSize(); i++) {
            QUser iUser = usersList.getModel().getElementAt(i);
            if (Objects.equals(iUser.getId(), selUser.getId())) {
                usersList.getSelectionModel().setSelectionInterval(i, i);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersList = new javax.swing.JList<>();
        redirectButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        commentTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        redirectBackCheckbox = new javax.swing.JCheckBox();
        aboRadioButton = new javax.swing.JRadioButton();
        scRadioButton = new javax.swing.JRadioButton();
        consultantRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Список пользователей для перенаправления:");

        usersList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        usersList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                usersListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(usersList);

        redirectButton.setText("Перенаправить");
        redirectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redirectButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Отмена");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        commentTextArea.setColumns(20);
        commentTextArea.setRows(5);
        jScrollPane2.setViewportView(commentTextArea);

        jLabel2.setText("Комментарий:");

        redirectBackCheckbox.setText("вернуть после обслуживания");
        redirectBackCheckbox.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        buttonGroup.add(aboRadioButton);
        aboRadioButton.setText("абон. зал");
        aboRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup.add(scRadioButton);
        scRadioButton.setText("СЦ");
        scRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scRadioButtonActionPerformed(evt);
            }
        });

        consultantRadioButton.setText("консультант");
        consultantRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultantRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(redirectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(redirectBackCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aboRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(scRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(consultantRadioButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(redirectBackCheckbox)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aboRadioButton)
                    .addComponent(scRadioButton)
                    .addComponent(consultantRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redirectButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        selectedUser = null;
        isCancelled = true;
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void redirectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redirectButtonActionPerformed
        selectedUser = usersList.getSelectedValue();
        setVisible(false);
    }//GEN-LAST:event_redirectButtonActionPerformed

    private void aboRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboRadioButtonActionPerformed
        pointType = Uses.POINT_TYPE_ABO;
        refreshUsers();
    }//GEN-LAST:event_aboRadioButtonActionPerformed

    private void scRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scRadioButtonActionPerformed
        pointType = Uses.POINT_TYPE_SC;
        refreshUsers();
    }//GEN-LAST:event_scRadioButtonActionPerformed

    private void usersListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_usersListValueChanged
        selectedUser = usersList.getSelectedValue();
    }//GEN-LAST:event_usersListValueChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        selectedUser = null;
    }//GEN-LAST:event_formWindowClosing

    private void consultantRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultantRadioButtonActionPerformed
        pointType = Uses.POINT_TYPE_CONSULTANT;
        refreshUsers();
    }//GEN-LAST:event_consultantRadioButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aboRadioButton;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextArea commentTextArea;
    private javax.swing.JRadioButton consultantRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox redirectBackCheckbox;
    private javax.swing.JButton redirectButton;
    private javax.swing.JRadioButton scRadioButton;
    private javax.swing.JList<QUser> usersList;
    // End of variables declaration//GEN-END:variables
}