/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.apertum.qsystem.client.forms;

import java.util.LinkedList;
import java.util.Objects;
import java.util.Timer;
import java.util.TimerTask;
import java.util.stream.Collectors;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import ru.apertum.qsystem.common.CustomerState;
import ru.apertum.qsystem.common.NetCommander;
import ru.apertum.qsystem.common.model.IClientNetProperty;
import ru.apertum.qsystem.common.model.QCustomer;

/**
 *
 * @author zaikov
 */
public class TicketsToRemoveWindow extends javax.swing.JDialog {

    private LinkedList<QCustomer> tickets;
    private final IClientNetProperty netProperty;
    private final Integer unitId;
    private Timer refreshTicketsTimer;
    
    public TicketsToRemoveWindow(java.awt.Frame parent, boolean modal, Integer unitId, IClientNetProperty netProperty) {
        super(parent, modal);
        initComponents();
        
        setTitle("Удаление талонов");
        setLocationRelativeTo(null);
        
        this.netProperty = netProperty;
        this.unitId = unitId;
        
        startRefreshTicketsTimer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ticketsList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        removeTicketsButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(ticketsList);

        jLabel1.setText("Талоны доступные для удаления:");

        removeTicketsButton.setText("Удалить");
        removeTicketsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTicketsButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Закрыть");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(removeTicketsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeTicketsButton)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void removeTicketsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTicketsButtonActionPerformed
        int count = 0;
        
        for (QCustomer ticket : ticketsList.getSelectedValuesList()) {
            NetCommander.killCustomer(
                    netProperty,
                    ticket.getId(),
                    unitId);
            count++;
        }
        
        if (count > 0) {
            JOptionPane.showMessageDialog(this, "Количество удалённых талонов " + count, "Внимание", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_removeTicketsButtonActionPerformed

    private void startRefreshTicketsTimer() {
        TimerTask task = new TimerTask() {
            
            @Override
            public void run() {
                
                LinkedList<QCustomer> oldTickets = tickets;
                
                //получаем список талонов и фильтруем по условиям
                tickets = (LinkedList<QCustomer>) NetCommander
                        .getTickets(netProperty, unitId).stream()
                        .filter(
                                t ->
                                    t.getState() == CustomerState.STATE_POSTPONED ||
                                    t.getState() == CustomerState.STATE_POSTPONED_AFTER_SERVICE ||
                                    t.getState() == CustomerState.STATE_WAIT || 
                                    t.getState() == CustomerState.STATE_WAIT_AFTER_PAYMENT ||
                                    t.getState() == CustomerState.STATE_WAIT_AFTER_POSTPONED ||
                                    t.getState() == CustomerState.STATE_REDIRECT
                        )
                        .collect(Collectors.toCollection(LinkedList::new));

                DefaultListModel<QCustomer> lm = new DefaultListModel<>();
                tickets.forEach(t -> {
                    lm.addElement(t);
                });
                ticketsList.setModel(lm);
                
                //выделяем талоны, которые были выделены до обновления
                for (int i = 0; i < ticketsList.getModel().getSize(); i++) {
                    QCustomer iTicket = ticketsList.getModel().getElementAt(i);
                    QCustomer oldTicket = oldTickets.get(i);
                    if (Objects.equals(iTicket.getId(), oldTicket.getId())) {
                        ticketsList.getSelectionModel().setSelectionInterval(i, i);
                    }
                }
            }
        };
        refreshTicketsTimer = new Timer();
        refreshTicketsTimer.scheduleAtFixedRate(task, 0L, 5000L);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeTicketsButton;
    private javax.swing.JList<QCustomer> ticketsList;
    // End of variables declaration//GEN-END:variables
}