action.custom-1=Run Server
action.custom-1.args=--configure-on-demand -w -x check runServer
action.custom-2=Run Client
action.custom-2.args=--configure-on-demand -w -x check runClient
action.custom-3=Run Session Manager
action.custom-3.args=--configure-on-demand -w -x check runSessionManager
action.custom-4=Run Reception
action.custom-4.args=--configure-on-demand -w -x check runReception
action.custom-5=Run Welcome
action.custom-5.args=--configure-on-demand -w -x check runWelcome
action.custom-6=Debug Server
action.custom-6.args=--configure-on-demand -w -x check debugServer
action.custom-7=Debug Client
action.custom-7.args=--configure-on-demand -w -x check debugClient
action.custom-8=Debug Session Manager
action.custom-8.args=--configure-on-demand -w -x check debugSessionManager
action.custom-9=Debug Reception
action.custom-9.args=--configure-on-demand -w -x check debugReception
action.custom-10=Debug Welcome
action.custom-10.args=--configure-on-demand -w -x check debugWelcome
