action.custom-1=Debug Server
action.custom-1.args=--configure-on-demand -w -x check debugServer --debug-jvm
action.custom-11=Debug Admin
action.custom-11.args=--configure-on-demand -w -x check debugAdmin --debug-jvm
action.custom-2=Debug Client
action.custom-2.args=--configure-on-demand -w -x check debugClient --debug-jvm
action.custom-3=Debug Session Manager
action.custom-3.args=--configure-on-demand -w -x check debugSessionManager --debug-jvm
action.custom-4=Debug Reception
action.custom-4.args=--configure-on-demand -w -x check debugReception --debug-jvm
action.custom-5=Debug Welcome
action.custom-5.args=--configure-on-demand -w -x check debugWelcome --debug-jvm
