action.custom-0=Run Server
action.custom-0.args=--configure-on-demand -w -x check runServer
action.custom-1=Debug Server
action.custom-1.args=--configure-on-demand -w -x check debugServer --no-daemon --debug-jvm
action.custom-2=Debug Admin
action.custom-2.args=--configure-on-demand -w -x check debugAdmin --debug-jvm
action.custom-3=Debug Client
action.custom-3.args=--configure-on-demand -w -x check debugClient --debug-jvm
action.custom-4=Run Client
action.custom-4.args=--configure-on-demand -w -x check runClient
action.custom-5=Debug Session Manager
action.custom-5.args=--configure-on-demand -w -x check debugSessionManager --debug-jvm
action.custom-6=Debug Reception
action.custom-6.args=--configure-on-demand -w -x check debugReception --debug-jvm
action.custom-7=Debug Welcome
action.custom-7.args=--configure-on-demand -w -x check debugWelcome --debug-jvm
