#Settings of admining and monitoring
#Fri May 30 11:02:06 EEST 2025
server_adress=10.2.41.79
client_auto_request=0
server_auto_request=0
client_adress=10.2.41.79
service_address=http\://10.2.41.79\:9901/queue
server_plugin_stat=dev
client_port=3129
server_port=3306
