#Settings of report sending
#Tue May 12 14:11:17 MSD 2009

# Включено или выключено. true/false    1/0
mailing=true
mail.smtp.port=25
mail.smtp.host=mail.int.idknet.com
mail.smtp.auth=true
mail.smtp.user=qsystem@admin.idknet.com
mail.password=123qweASD
mail.smtp.from=qsystem@admin.idknet.com
mail.smtp.to=77544827@sms.idknet.com

mail.smtp.starttls.enable=false
mail.mime.charset=UTF-8
mail.subject=QSystem. Report: Ежедневный отчет о распределении нагрузки внутри дня

# файл содержания письма или строка содержания письма / text of message or file
mail.content=config/reporter.html

# Paper running out / израсходование бумаги
#  true/false    1/0
paper_alarm_mailing=true
#5 - Тирасполь, 6 - Бендеры, 7 - Рыбница
mail.smtp.paper_alarm_to.5=77544827@sms.idknet.com,a.zaikov@billing.idknet.com
mail.smtp.paper_alarm_to.6=77544827@sms.idknet.com,a.zaikov@billing.idknet.com
mail.smtp.paper_alarm_to.7=77544827@sms.idknet.com,a.zaikov@billing.idknet.com
mail.smtp.start_stop=77544827@sms.idknet.com,a.zaikov@billing.idknet.com
mail.paper_alarm_subject=QSystem. Израсходование бумаги
