#Version of the system
#Mon Mar 02 19:02:10 MSK 2009
cmrc=0
#date используется для автообновления FReception
#если date не равен значению date_reception из таблицы software_version, то нужно обновиться
#date должен быть в формате yyyy-MM-dd HH:mm:ss
date=2018-07-06 08:00:00
version=18.3.3
version_db=5
name=<html><p align='right'><span style='color: yellow; font-size: 15'>Primus inter pares</span><br/><span style='color: white; font-size: 12'>v18.3.3<br/>www.qsystem.info</span></p>
nameV2=<html><p align='right'><span style='color: yellow; font-size: 15'>slogan</span><br/><span style='color: white; font-size: 12'>version<br/>web</span></p></html>
slogan=Primus inter pares
web=www.qsystem.info